# Generated by Django 4.2 on 2026-03-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="公告标题")),
                ("content", models.TextField(verbose_name="公告内容")),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="是否发布"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="发布时间"),
                ),
            ],
            options={
                "verbose_name": "公告",
                "verbose_name_plural": "公告",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Banner 标题")),
                (
                    "subtitle",
                    models.CharField(blank=True, max_length=255, verbose_name="副标题"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="banners/",
                        verbose_name="Banner 图片",
                    ),
                ),
                ("link", models.URLField(blank=True, verbose_name="跳转链接")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "Banner",
                "verbose_name_plural": "Banner",
                "ordering": ["-created_at"],
            },
        ),
    ]
