# Generated by Django 4.2 on 2026-03-10 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="分类名称"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="分类说明")),
            ],
            options={
                "verbose_name": "课程分类",
                "verbose_name_plural": "课程分类",
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="课程名称")),
                (
                    "cover",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="course_covers/",
                        verbose_name="课程封面",
                    ),
                ),
                ("summary", models.CharField(max_length=255, verbose_name="课程简介")),
                ("description", models.TextField(blank=True, verbose_name="课程详情")),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "草稿"), ("published", "已发布")],
                        default="published",
                        max_length=20,
                        verbose_name="课程状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="courses",
                        to="courses.coursecategory",
                        verbose_name="分类",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teaching_courses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="授课教师",
                    ),
                ),
            ],
            options={
                "verbose_name": "课程",
                "verbose_name_plural": "课程",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CourseEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="加入时间"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="courses.course",
                        verbose_name="课程",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="学生",
                    ),
                ),
            ],
            options={
                "verbose_name": "选课记录",
                "verbose_name_plural": "选课记录",
                "unique_together": {("course", "student")},
            },
        ),
    ]
