# Generated by Django 4.2 on 2026-04-03 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0002_coursetag_courseviewlog_course_tags_coursefavorite"),
        ("assignments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIInteractionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("lesson_prep", "AI 备课"),
                            ("lesson_teaching", "AI 授课"),
                            ("evaluation", "AI 评价"),
                            ("grading", "AI 辅助批阅"),
                            ("plagiarism", "AI 查重"),
                        ],
                        max_length=32,
                        verbose_name="AI 模式",
                    ),
                ),
                ("prompt", models.TextField(verbose_name="输入内容")),
                ("response", models.TextField(verbose_name="AI 输出")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_logs",
                        to="assignments.assignment",
                        verbose_name="作业",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_logs",
                        to="courses.course",
                        verbose_name="课程",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_logs",
                        to="assignments.assignmentsubmission",
                        verbose_name="作业提交",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="教师",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI 交互记录",
                "verbose_name_plural": "AI 交互记录",
                "ordering": ["-created_at"],
            },
        ),
    ]
