# Generated by Django 4.2 on 2026-04-03 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discussions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="discussionpost",
            name="post_type",
            field=models.CharField(
                choices=[
                    ("general", "普通讨论"),
                    ("classroom", "课堂讨论"),
                    ("group", "分组讨论"),
                ],
                default="general",
                max_length=20,
                verbose_name="讨论类型",
            ),
        ),
    ]
