# Generated by Django 4.2 on 2026-03-10 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="资料标题")),
                (
                    "material_type",
                    models.CharField(
                        choices=[
                            ("document", "文档"),
                            ("video", "视频"),
                            ("link", "外部链接"),
                        ],
                        default="document",
                        max_length=20,
                        verbose_name="资料类型",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="资料说明")),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="materials/",
                        verbose_name="文件",
                    ),
                ),
                ("external_url", models.URLField(blank=True, verbose_name="外部链接")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="上传时间"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="courses.course",
                        verbose_name="所属课程",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_materials",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="上传教师",
                    ),
                ),
            ],
            options={
                "verbose_name": "教学资料",
                "verbose_name_plural": "教学资料",
                "ordering": ["-created_at"],
            },
        ),
    ]
