# Generated by Django 4.2 on 2026-04-03 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursematerial",
            name="content",
            field=models.TextField(blank=True, verbose_name="资料正文"),
        ),
        migrations.AlterField(
            model_name="coursematerial",
            name="external_url",
            field=models.URLField(blank=True, verbose_name="参考链接"),
        ),
        migrations.AlterField(
            model_name="coursematerial",
            name="material_type",
            field=models.CharField(
                choices=[
                    ("document", "文档"),
                    ("video", "视频"),
                    ("link", "站内链接资料"),
                ],
                default="document",
                max_length=20,
                verbose_name="资料类型",
            ),
        ),
    ]
