# Generated by Django 4.2 on 2026-04-03 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0002_coursetag_courseviewlog_course_tags_coursefavorite"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="签到标题")),
                ("description", models.TextField(blank=True, verbose_name="签到说明")),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "进行中"), ("closed", "已结束")],
                        default="open",
                        max_length=20,
                        verbose_name="签到状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="发起时间"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_sessions",
                        to="courses.course",
                        verbose_name="课程",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_attendance_sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="教师",
                    ),
                ),
            ],
            options={
                "verbose_name": "签到活动",
                "verbose_name_plural": "签到活动",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "signed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="签到时间"),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="attendance.attendancesession",
                        verbose_name="签到活动",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="学生",
                    ),
                ),
            ],
            options={
                "verbose_name": "签到记录",
                "verbose_name_plural": "签到记录",
                "ordering": ["signed_at"],
                "unique_together": {("session", "student")},
            },
        ),
    ]
